/**
 * The data layer against the real Neon + Upstash. Nothing is mocked on purpose:
 * the whole point is that a 1024² PNG survives a round-trip through `bytea` and
 * through Upstash's JSON/REST transport byte for byte, and a fake would prove
 * nothing.
 *
 * Every row and key is tagged with a per-run id so concurrent runs cannot
 * collide, `after()` deletes them by primary key even if a test threw, and with
 * no credentials every test skips rather than fails.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { deflateSync } from 'node:zlib';
import { after, before, describe, test } from 'node:test';

import { eq, inArray } from 'drizzle-orm';

import { hasDatabase } from '../dist/env.js';
import { avatars, closeDb, db, lobbies, lobbyMembers, players, textures } from '../dist/db.js';
import { lobbyPlayersKey, redis, textureKey } from '../dist/redis.js';

const RUN_ID = `t${randomUUID().replace(/-/g, '').slice(0, 10)}`;
const hasRedis = redis.configured;
const skipPg = !hasDatabase() && 'no DATABASE_URL — skipping real-Neon test';
const skipRedis = !hasRedis && 'no UPSTASH_REDIS_REST_* — skipping real-Upstash test';
const skipBoth = skipPg || skipRedis;

/** Ids/keys to remove in `after()`; appended to as soon as anything is created. */
const created = { players: [], avatars: [], textures: [], lobbies: [], redisKeys: [] };

// ---------------------------------------------------------------------------
// A genuinely valid (tiny) PNG, so the bytes we round-trip are real image bytes
// with a real sha256 content address — not a random blob.
// ---------------------------------------------------------------------------
const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
function crc32(buf) {
  let c = 0xffffffff;
  for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}
/** RGBA PNG of `size`×`size`, pixels derived from `seed` so each run differs. */
function makePng(size, seed) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type RGBA
  const raw = Buffer.alloc(size * (size * 4 + 1));
  let h = 0;
  for (const ch of seed) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  for (let y = 0; y < size; y++) {
    const row = y * (size * 4 + 1);
    raw[row] = 0; // filter: none
    for (let x = 0; x < size; x++) {
      h = (h * 1664525 + 1013904223) >>> 0;
      const p = row + 1 + x * 4;
      raw[p] = h & 0xff;
      raw[p + 1] = (h >>> 8) & 0xff;
      raw[p + 2] = (h >>> 16) & 0xff;
      raw[p + 3] = 0xff;
    }
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

const TEXTURE = makePng(32, RUN_ID);
const TEXTURE_HASH = createHash('sha256').update(TEXTURE).digest('hex');

describe('Chunk 3.1 data layer (real Neon + Upstash)', () => {
  before(() => {
    if (skipBoth) return;
    // Sanity: a PNG whose bytes we later compare must not be trivially small.
    assert.ok(TEXTURE.length > 1000, `expected a non-trivial PNG, got ${TEXTURE.length} bytes`);
    assert.equal(TEXTURE.subarray(1, 4).toString('ascii'), 'PNG');
  });

  test('texture + wearer round-trip keeps bytes identical, and one drawing has many wearers', { skip: skipPg }, async () => {
    const [player] = await db()
      .insert(players)
      .values({ name: `${RUN_ID}-ada` })
      .returning();
    created.players.push(player.id);

    assert.ok(player.id, 'player id should be generated by gen_random_uuid()');
    assert.equal(player.name, `${RUN_ID}-ada`);
    assert.ok(player.createdAt instanceof Date);

    // The blob lives in its own content-addressed table.
    await db().insert(textures).values({ hash: TEXTURE_HASH, bytes: TEXTURE });
    created.textures.push(TEXTURE_HASH);

    const [storedTexture] = await db().select().from(textures).where(eq(textures.hash, TEXTURE_HASH));
    assert.ok(Buffer.isBuffer(storedTexture.bytes), 'bytea must come back as a Buffer');
    assert.equal(storedTexture.bytes.length, TEXTURE.length);
    assert.ok(storedTexture.bytes.equals(TEXTURE), 'texture bytes must be byte-identical');
    assert.equal(
      createHash('sha256').update(storedTexture.bytes).digest('hex'),
      TEXTURE_HASH,
      'sha256 of the stored texture must equal its content address',
    );

    // Storing the same drawing twice is a no-op, not a fight over ownership.
    const reinsert = await db()
      .insert(textures)
      .values({ hash: TEXTURE_HASH, bytes: TEXTURE })
      .onConflictDoNothing({ target: textures.hash })
      .returning({ hash: textures.hash });
    assert.equal(reinsert.length, 0, 're-storing identical bytes must change nothing');

    const [avatar] = await db()
      .insert(avatars)
      .values({ playerId: player.id, modelSlug: 'trex', textureHash: TEXTURE_HASH, sourcePhoto: null })
      .returning({ id: avatars.id });
    created.avatars.push(avatar.id);

    const [readBack] = await db().select().from(avatars).where(eq(avatars.id, avatar.id));
    assert.equal(readBack.modelSlug, 'trex');
    assert.equal(readBack.textureHash, TEXTURE_HASH);
    assert.equal(readBack.sourcePhoto, null);

    // ── The "one texture, one owner" sharp edge, in the schema ─────────────
    // A SECOND player wearing byte-identical pixels is now perfectly legal…
    const [other] = await db()
      .insert(players)
      .values({ name: `${RUN_ID}-bob` })
      .returning({ id: players.id });
    created.players.push(other.id);

    const [shared] = await db()
      .insert(avatars)
      .values({ playerId: other.id, modelSlug: 'stego', textureHash: TEXTURE_HASH })
      .returning({ id: avatars.id });
    created.avatars.push(shared.id);
    assert.notEqual(shared.id, avatar.id, 'two wearers of one drawing are two rows');

    const wearers = await db().select().from(avatars).where(eq(avatars.textureHash, TEXTURE_HASH));
    assert.equal(wearers.length, 2, 'one texture, two owners');

    // …while a second avatar row for the SAME player is not: player_id is
    // UNIQUE, so a retake replaces the drawing rather than stacking up.
    // (Drizzle wraps driver errors and its `message` embeds the whole query, so
    // assert on the pg SQLSTATE in `cause` instead.)
    let dupe;
    try {
      const [row] = await db()
        .insert(avatars)
        .values({ playerId: player.id, modelSlug: 'raptor', textureHash: TEXTURE_HASH })
        .returning({ id: avatars.id });
      created.avatars.push(row.id);
    } catch (err) {
      dupe = err;
    }
    assert.ok(dupe, 'inserting a second avatar for the same player must fail');
    assert.equal(dupe.cause?.code ?? dupe.code, '23505', 'expected unique_violation on player_id');

    // The FK is real: a wearer cannot point at a drawing nobody stored.
    const [third] = await db()
      .insert(players)
      .values({ name: `${RUN_ID}-cy` })
      .returning({ id: players.id });
    created.players.push(third.id);

    let orphan;
    try {
      await db()
        .insert(avatars)
        .values({ playerId: third.id, modelSlug: 'bronto', textureHash: 'a'.repeat(64) });
    } catch (err) {
      orphan = err;
    }
    assert.equal(orphan?.cause?.code ?? orphan?.code, '23503', 'expected a foreign_key_violation');
  });

  test('lobby + lobby_members persist and join by code', { skip: skipPg }, async () => {
    const code = RUN_ID.slice(0, 5).toUpperCase();
    const [lobby] = await db()
      .insert(lobbies)
      .values({ code, name: `${RUN_ID} lobby` })
      .returning();
    created.lobbies.push(lobby.id);

    const [player] = await db()
      .insert(players)
      .values({ name: `${RUN_ID}-grace` })
      .returning({ id: players.id });
    created.players.push(player.id);

    await db().insert(lobbyMembers).values({ lobbyId: lobby.id, playerId: player.id });

    const rows = await db()
      .select({ name: players.name, joinedAt: lobbyMembers.joinedAt })
      .from(lobbyMembers)
      .innerJoin(players, eq(players.id, lobbyMembers.playerId))
      .innerJoin(lobbies, eq(lobbies.id, lobbyMembers.lobbyId))
      .where(eq(lobbies.code, code));

    assert.equal(rows.length, 1);
    assert.equal(rows[0].name, `${RUN_ID}-grace`);
    assert.ok(rows[0].joinedAt instanceof Date);
    assert.equal(lobby.closedAt, null, 'a fresh lobby is open');
  });

  test('redis texture cache set/get is byte-identical', { skip: skipRedis }, async () => {
    created.redisKeys.push(textureKey(TEXTURE_HASH));

    assert.equal(await redis.getTexture(TEXTURE_HASH), null, 'cold cache must miss');

    await redis.setTexture(TEXTURE_HASH, TEXTURE, 300);
    const cached = await redis.getTexture(TEXTURE_HASH);

    assert.ok(Buffer.isBuffer(cached), 'cache hit must be a Buffer');
    assert.equal(cached.length, TEXTURE.length);
    assert.ok(cached.equals(TEXTURE), 'cached texture bytes must be byte-identical');
    assert.equal(createHash('sha256').update(cached).digest('hex'), TEXTURE_HASH);

    const ttl = await redis.client().ttl(textureKey(TEXTURE_HASH));
    assert.ok(Number(ttl) > 0 && Number(ttl) <= 300, `expected a live TTL, got ${ttl}`);
  });

  test('redis lobby membership add/list/remove round-trip', { skip: skipRedis }, async () => {
    const code = `${RUN_ID}-lobby`;
    const [a, b] = [`${RUN_ID}-p1`, `${RUN_ID}-p2`];
    created.redisKeys.push(lobbyPlayersKey(code));

    assert.deepEqual(await redis.listLobbyMembers(code), [], 'empty lobby lists nothing');

    assert.equal(await redis.addLobbyMember(code, a), true);
    assert.equal(await redis.addLobbyMember(code, b), true);
    assert.equal(await redis.addLobbyMember(code, a), false, 're-add is idempotent');

    assert.deepEqual([...(await redis.listLobbyMembers(code))].sort(), [a, b].sort());

    assert.equal(await redis.removeLobbyMember(code, a), true);
    assert.equal(await redis.removeLobbyMember(code, a), false, 'removing twice is a no-op');
    assert.deepEqual(await redis.listLobbyMembers(code), [b]);
  });

  test('publishAvatarUpdate reaches redis without a subscriber', { skip: skipRedis }, async () => {
    const receivers = await redis.publishAvatarUpdate({
      lobbyCode: RUN_ID.slice(0, 5).toUpperCase(),
      playerId: randomUUID(),
      modelSlug: 'raptor',
      textureHash: TEXTURE_HASH,
    });
    // Nobody is listening in this test, so 0 is the correct answer — we're
    // asserting the command is accepted, not that it was delivered.
    assert.equal(typeof receivers, 'number');
    assert.ok(receivers >= 0);
  });

  test('ping is green for both services', { skip: skipBoth }, async () => {
    assert.equal(await redis.ping(), true);
  });

  after(async () => {
    const problems = [];
    // Children first: avatars + lobby_members reference players/lobbies.
    for (const [label, fn] of [
      ['avatars', () => created.avatars.length && db().delete(avatars).where(inArray(avatars.id, created.avatars))],
      [
        'textures',
        () => created.textures.length && db().delete(textures).where(inArray(textures.hash, created.textures)),
      ],
      [
        'lobby_members',
        () =>
          created.lobbies.length &&
          db().delete(lobbyMembers).where(inArray(lobbyMembers.lobbyId, created.lobbies)),
      ],
      ['lobbies', () => created.lobbies.length && db().delete(lobbies).where(inArray(lobbies.id, created.lobbies))],
      ['players', () => created.players.length && db().delete(players).where(inArray(players.id, created.players))],
      ['redis keys', () => created.redisKeys.length && redis.del(...created.redisKeys)],
    ]) {
      try {
        await fn();
      } catch (err) {
        problems.push(`${label}: ${err instanceof Error ? err.message : err}`);
      }
    }
    try {
      await closeDb();
    } catch {
      /* pool may never have opened */
    }
    if (problems.length) {
      throw new Error(`cleanup left rows behind (run id ${RUN_ID}) — ${problems.join('; ')}`);
    }
  });
});
